# Generated by Django 5.2.4 on 2025-07-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='chief_guest_name',
            field=models.TextField(null=True),
        ),
    ]
