# Generated by Django 5.2.4 on 2025-07-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_details_chief_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='inaugartion_time',
            field=models.TimeField(null=True),
        ),
    ]
