# Generated by Django 5.2.4 on 2025-07-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_details_inaugartion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='events_time',
            field=models.TextField(default='11.00am-4.30pm'),
        ),
        migrations.AlterField(
            model_name='details',
            name='inaugartion_time',
            field=models.TextField(null=True),
        ),
    ]
