# Generated by Django 5.2.4 on 2025-07-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_details_events_time_alter_details_inaugartion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='optazia',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='details',
            name='sthithapragya',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='details',
            name='xenora',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
