# Generated by Django 5.2.4 on 2025-07-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_details_optazia_details_sthithapragya_details_xenora'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='chief_guest_poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='details',
            name='inaugration_poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='details',
            name='main_poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='optazia',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='sthithapragya',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='xenora',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
