# Generated by Django 5.2.4 on 2025-08-06 16:24
from django.db import migrations

def create_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='passadmin1'  # Change to a strong password
        )

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20250806_2154.py'),  # Replace with your last migration name
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]