# Generated by Django 5.2.4 on 2025-08-06 17:09

from django.db import migrations

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'passadmin1')



class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_details_logo'),
    ]

    operations = [
    ]
    operations = [
        migrations.RunPython(create_superuser),
    ]
