# Generated by Django 5.2.4 on 2025-07-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.events')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.school')),
            ],
        ),
    ]
