# Generated by Django 5.2.4 on 2025-07-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_participant_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_details',
            name='school',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='form.school'),
        ),
        migrations.AddField(
            model_name='events',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form.main_events'),
        ),
        migrations.AddField(
            model_name='events',
            name='is_team_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='max_team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='max_teams_per_school',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
