# Generated by Django 5.2.4 on 2025-08-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_basic_details_school_events_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='max_team_size',
        ),
    ]
